Inclass Example

In [5]:
import numpy as np
A = np.array(([2,-1],[3,2],[2,-3]))
B = np.array(([2,-2],[-5,3]))
C = A@B
print(C)

[[  9  -7]
 [ -4   0]
 [ 19 -13]]


1. 
i) solve the system by hand
ii) check using np.linalg.solve(A,B)

In [1]:
import numpy as np
A = np.array([[2,3,3],[1,3,1],[-2,-4,-4]])
b = np.array([9,8,-10])
print(np.linalg.solve(A,b))

[ 3.  2. -1.]


2. 
i create matrix A
ii create 4 vectors containing the columns of A; put them together to form a new variable equal to A using np.column_stack
iii create 3 vectors containing the rows of A; put them together to form a new variable equalt o A using np.row_stack

In [6]:
import numpy as np
A = np.array([(0,-2.3,0,-2),(1,-2,0,0),(0,0,4.3,5)])
print(A)
print("\n")
c1 = np.array([0, 1, 0])
c2 = np.array([-2.3, -2, 0])
c3 = np.array([0, 0, 4.3])
c4 = np.array([-2, 0, 5])
print(np.column_stack((c1,c2,c3,c4)))
print("\n")
r1 = np.array([0,-2.3,0,-2])
r2 = np.array([1,-2,0,0])
r3 = np.array([0,0,4.3,5])
print(np.row_stack((r1,r2,r3)))


[[ 0.  -2.3  0.  -2. ]
 [ 1.  -2.   0.   0. ]
 [ 0.   0.   4.3  5. ]]


[[ 0.  -2.3  0.  -2. ]
 [ 1.  -2.   0.   0. ]
 [ 0.   0.   4.3  5. ]]


[[ 0.  -2.3  0.  -2. ]
 [ 1.  -2.   0.   0. ]
 [ 0.   0.   4.3  5. ]]


3. Given Matricies A, B, C

i) which is defined? AB, BA, AC, CA, BC, CB
ii) chose two products that are defined and compute by hand
iii) enter each as arrays and verify your calculations

In [17]:
import numpy as np
A = np.array([[2,0,-1],[2,3.5,-3]])
B = np.array([[1,-2],[3,4]])
C = np.array([[3,2],[1,1],[2,-5]])

print("AC = ",A@C)
print('\n')
print("BA = ",B@A)



AC =  [[ 4.   9. ]
 [ 3.5 22.5]]


BA =  [[ -2.  -7.   5.]
 [ 14.  14. -15.]]


4. Given Matricies A and B
i. enter as numpy arrays
ii) compute AB, AB^T, A^T * B^T, and B^T * A^T transpose; confirmt that AB transpose = BT * AT and not A^T * B^T

In [14]:
a1 = np.array([-3, 1, -0, 3, -4])
a2 = np.array([3, -2, -4, 0, 4])
a3 = np.array([-2, 1, -2, 4, -4])
a4 = np.array([0, 2, 4, -4, 2])
a5 = np.array([-3, 2, -3, -1, 3])
A = np.row_stack((a1, a2, a3, a4, a5))
#print(A)
print("\n")
b1 = np.array([-3, 0, -3, 4, -2])
b2 = np.array([1, -2, -1, 2, 0])
b3 = np.array([2, 2, 1, 0, 0])
b4 = np.array([1, -3, 3, -1, 3])
b5 = np.array([0, 2, -4, 0, 3])
B = np.row_stack((b1, b2, b3, b4, b5))
print(B)
print("\n")

print("AB")
AB = A * B
print(AB)
print("\n")

ABT = np.transpose(AB)
print("ABT")
print(ABT)
print("\n")

AT = np.transpose(A)
BT = np.transpose(B)
ATBT = AT*BT
BTAT = BT*AT

print("BT*AT")
print(BTAT)
print("\n")

print("AT*BT")
print(ATBT)
print("\n")

print("x\n")
x = np.linalg.solve(A,np.array([1, -2, 3, -4, 5]))
print(x)

v = np.array([2,0,3,1,2.4])
Av = A*v
x2 = np.linalg.solve(B,Av)
print("x2 = ")
print(x2)





[[-3  0 -3  4 -2]
 [ 1 -2 -1  2  0]
 [ 2  2  1  0  0]
 [ 1 -3  3 -1  3]
 [ 0  2 -4  0  3]]


AB
[[ 9  0  0 12  8]
 [ 3  4  4  0  0]
 [-4  2 -2  0  0]
 [ 0 -6 12  4  6]
 [ 0  4 12  0  9]]


ABT
[[ 9  3 -4  0  0]
 [ 0  4  2 -6  4]
 [ 0  4 -2 12 12]
 [12  0  0  4  0]
 [ 8  0  0  6  9]]


BT*AT
[[ 9  3 -4  0  0]
 [ 0  4  2 -6  4]
 [ 0  4 -2 12 12]
 [12  0  0  4  0]
 [ 8  0  0  6  9]]


AT*BT
[[ 9  3 -4  0  0]
 [ 0  4  2 -6  4]
 [ 0  4 -2 12 12]
 [12  0  0  4  0]
 [ 8  0  0  6  9]]


x

[-0.60377358 -1.1509434  -4.98113208 -7.35849057 -5.60377358]
x2 = 
[[ 2.50000000e+00 -0.00000000e+00 -6.00000000e+00  4.37500000e-01
   3.00000000e+00]
 [-3.35526316e+00 -0.00000000e+00  7.89473684e-01  1.26151316e+00
  -5.22631579e+00]
 [-2.28947368e+00 -0.00000000e+00  4.42105263e+00  6.01973684e-01
  -5.14736842e+00]
 [-2.75000000e+00  0.00000000e+00 -1.27821730e-17  1.34375000e+00
  -4.50000000e+00]
 [-2.81578947e+00  0.00000000e+00  2.36842105e+00 -3.71710526e-01
  -9.78947368e-01]]
