Inclass Example

In [5]:
import numpy as np
A = np.array(([2,-1],[3,2],[2,-3]))
B = np.array(([2,-2],[-5,3]))
C = A@B
print(C)

[[  9  -7]
 [ -4   0]
 [ 19 -13]]


Example 2 (partitioning?)

Example 3 (non commutativity)

i) solve the system by hand
ii) check using np.linalg.solve(A,B)

In [7]:
import numpy as np
A = np.array([[2,3,3],[1,3,1],[-2,-4,-4]])
b = np.array([9,8,-10])
print(np.linalg.solve(A,b))

[ 3.  2. -1.]


i column stack
ii row stack

In [16]:
import numpy as np
A = np.array([(0,-2.3,0,-2),(1,-2,0,0),(0,0,4.3,5)])
print(np.column_stack((A[0],A[1],A[2])))


[[ 0.   1.   0. ]
 [-2.3 -2.   0. ]
 [ 0.   0.   4.3]
 [-2.   0.   5. ]]


i) which is defined? AB, BA, AC, CA, BC, CB
ii) chose two products that are defined and compute by hand
iii) enter each as arrays and verify your calculations

In [17]:
import numpy as np
A = np.array([[2,0,-1],[2,3.5,-3]])
B = np.array([[1,-2],[3,4]])
C = np.array([[3,2],[1,1],[2,-5]])

print("AC = ",A@C)
print('\n')
print("BA = ",B@A)



AC =  [[ 4.   9. ]
 [ 3.5 22.5]]


BA =  [[ -2.  -7.   5.]
 [ 14.  14. -15.]]
